import { Container } from "inversify";
import { TYPES } from "./types";
import { CustomerRepositoy } from './src/repository/customer.repository';
import { CustomerService } from "./src/servicies/customer.service";
import { IAuthService } from "./src/servicies/interfaces/auth.interface";
import { AuthService } from "./src/servicies/auth.service";
import { ICustomerRepository } from "./src/repository/interfaces/customer-repository.interface";
import { TourRepositoy } from "./src/repository/tour.repository";
import { ITourRepository } from "./src/repository/interfaces/tour-repository.interface";
import { TourService } from "./src/servicies/tour.service";
import { GuideRepositoy } from "./src/repository/guide.repository";
import { IGuideRepository } from "./src/repository/interfaces/guide-repository.interface";
import { GuideService } from "./src/servicies/guide.service";
import { PortalService } from "./src/servicies/portal.service";
import { IPortalRepository } from "./src/repository/interfaces/portal-repository.interface";
import { PortalRepositoy } from "./src/repository/portal.repository";
import { IGuideRoleRepository } from "./src/repository/interfaces/guide-role-repository.interface";
import { GuideRoleRepositoy } from "./src/repository/guide-role.repository";
import { IManualRepository } from "./src/repository/interfaces/manual-repository.interface";
import { ManualRepositoy } from "./src/repository/manual.repository";
import { ManualService } from "./src/servicies/manual.service";
import { ReviewRepositoy } from "./src/repository/review.repository";
import { IReviewRepository } from "./src/repository/interfaces/review-repository.interface";
import { ReviewDetailRepositoy } from "./src/repository/review-detail.repository";
import { IReviewDetailRepository } from "./src/repository/interfaces/review-detail-repository.interface";
import { ISystemUserRepository } from "./src/repository/interfaces/system-user-repository.interface";
import { SystemUserRepository } from "./src/repository/system-user.repository";
import { UserService } from "./src/servicies/users.service";
import { TourAppRepository } from "./src/repository/tour-app.repository";
import { ITourAppRepository } from "./src/repository/interfaces/tour-app-repostitory.interface";
import { IPaymentRepository } from "./src/repository/interfaces/payment-repository.interface";
import { PaymentRepository } from "./src/repository/payment.repository";
import { IPaymentTypeRepository } from "./src/repository/interfaces/payment-type-repository.interface";
import { IExpenseRepository } from "./src/repository/interfaces/expense-repository.interface";
import { PaymentTypeRepository } from "./src/repository/payment-type.repository";
import { ExpenseRepository } from "./src/repository/expene.repository";
import { ExpenseService } from "./src/servicies/expene.service";
import { PaymentService } from "./src/servicies/payment.service";
import { GuideReviewService } from "./src/servicies/guide-review.service";
import { IGuideReviewReposiotry } from "./src/repository/interfaces/guide-review-repository.interface";
import { GuideReviewRepository } from "./src/repository/guide-review.repository";
import { RoleService } from "./src/servicies/role.service";
import { IRoleRepository } from "./src/repository/interfaces/role-repository.interface";
import { RoleRepository } from "./src/repository/role.repository";
import { ISeoRepository } from "./src/repository/interfaces/seo-repository.interface";
import { SeoRepository } from "./src/repository/seo.repository";
import { SeoService } from "./src/servicies/seo.service";

const container = new Container();

container.bind<ICustomerRepository>(TYPES.CustomerRepositoy).to(CustomerRepositoy);
container.bind<ITourRepository>(TYPES.TourRepositoy).to(TourRepositoy);
container.bind<IReviewRepository>(TYPES.ReviewRepositoy).to(ReviewRepositoy);
container.bind<IReviewDetailRepository>(TYPES.ReviewDetailRepositoy).to(ReviewDetailRepositoy);
container.bind<IGuideRepository>(TYPES.GuideRepositoy).to(GuideRepositoy);
container.bind<IGuideRoleRepository>(TYPES.GuideRoleRepositoy).to(GuideRoleRepositoy);
container.bind<IPortalRepository>(TYPES.PortalRepositoy).to(PortalRepositoy);
container.bind<ISystemUserRepository>(TYPES.SystemUserRepository).to(SystemUserRepository);
container.bind<IPaymentRepository>(TYPES.PaymentRepository).to(PaymentRepository);
container.bind<ITourAppRepository>(TYPES.TourAppRepository).to(TourAppRepository);
container.bind<IExpenseRepository>(TYPES.ExpenseRepository).to(ExpenseRepository);
container.bind<IPaymentTypeRepository>(TYPES.PaymentTypeRepository).to(PaymentTypeRepository);
container.bind<IManualRepository>(TYPES.ManualRepositoy).to(ManualRepositoy);
container.bind<IGuideReviewReposiotry>(TYPES.GuideReviewRepository).to(GuideReviewRepository);
container.bind<IRoleRepository>(TYPES.RoleRepository).to(RoleRepository);
container.bind<ISeoRepository>(TYPES.SeoRepository).to(SeoRepository);


container.bind<CustomerService>(TYPES.CustomerService).to(CustomerService);
container.bind<TourService>(TYPES.TourService).to(TourService);
container.bind<GuideService>(TYPES.GuideService).to(GuideService);
container.bind<PortalService>(TYPES.PortalService).to(PortalService);
container.bind<ManualService>(TYPES.ManualService).to(ManualService);
container.bind<UserService>(TYPES.UserService).to(UserService);
container.bind<IAuthService>(TYPES.AuthService).to(AuthService);
container.bind<ExpenseService>(TYPES.ExpenseService).to(ExpenseService);
container.bind<PaymentService>(TYPES.PaymentService).to(PaymentService);
container.bind<GuideReviewService>(TYPES.GuideReviewService).to(GuideReviewService);
container.bind<RoleService>(TYPES.RoleService).to(RoleService);
container.bind<SeoService>(TYPES.SeoService).to(SeoService);

export { container };